<<<<<<< HEAD
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
=======
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
>>>>>>> 7d53cc43b48b94701e6bc52cb7f874bb98e09642
};

function Header() {
  return (
    <header>
      <div>
        <nav>
          <div>
            <Link href="/">Snowtooth Mountain</Link>
          </div>
          <div>
            <Link href="/mountain">Mountain Info</Link>
          </div>
        </nav>
<<<<<<< HEAD

      </div>
    </header>

  )
=======
      </div>
    </header>
  );
>>>>>>> 7d53cc43b48b94701e6bc52cb7f874bb98e09642
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
=======
      <body className={inter.className}>
>>>>>>> 7d53cc43b48b94701e6bc52cb7f874bb98e09642
        <Header />
        {children}
      </body>
    </html>
  );
}
